Just about finished refactoring into farmerge

diff --git a/farmerge/modules/build b/farmerge/modules/build
--- a/farmerge/modules/build
+++ b/farmerge/modules/build
@@ -1,59 +1,21 @@
 #!/bin/bash
 
-source "${MODULES_BASEDIR}/lib"
+understood_args=( "BUILD_ACTION" "CPV" "BUILD_DIR" "STAGING_SSH_URI" "STAGING_SSH_PATH" "MIRROR_SSH_URI" "MIRROR_SSH_PATH" "MIRROR_HTTP_URI" "LOCK_SSH_URI" "LOCK_SSH_PATH" )
 
-understood_args=( "ACTION" "CPV" "BUILD_DIR" "STAGING_SSH_URI" "STAGING_SSH_PATH" "MIRROR_SSH_URI" "MIRROR_SSH_PATH" "MIRROR_HTTP_URI" "LOCK_SSH_URI" "LOCK_SSH_PATH" )
+source "${LIB_BASEDIR}/variable-args" || exit $?
 
-source "${LIB_BASEDIR}/variable-args"
+if [[ "${BUILD_ACTION}" == "" ]]; then
+	BUILD_ACTION="build"
+	echo "--$(machine_to_human_arg BUILD_ACTION) is empty, defaulting to: ${BUILD_ACTION}"
+fi
 
-for i in "${understood_args[@]}"; do
-	if [[ $(eval echo '${'"${i}"'}') == "" ]]; then
-		if [[ "${i}" == "ACTION" ]]; then
-			ACTION="add"
-			echo "--action empty, using default: ${ACTION}"
-		else
-			echo "Error: --"$(machine_to_human_arg "${i}")" required!"
-			exit 255
-		fi
-	fi
-done
+check_for_required_args "${understood_args[@]}" || exit $?
 
-exit
-
-binpkg_dir="/binpkgs"
-dist_dir="/tmp/distdir"
 rsync_args=( -cav --progress --delete --exclude='.lock' --exclude='.staging' )
 
-trap 'takedown_chroot "${BUILD_DIR}"
-      if [[ "${lock_acquired}" == "1" ]]; then unlock_mirror "${LOCK_SSH_URI}" "${LOCK_SSH_PATH}"; fi' 0
-# the following handler will exit the script on receiving these signals
-# the trap on "0" (EXIT) from above will be triggered by this trap's "exit" command
-trap 'echo "Killed." >&2
-      exit 1' 1 2 3 15
+"${MODULES_BASEDIR}/_exec-module" mirror-lock --mirror-action lock --lock-ssh-uri "${LOCK_SSH_URI}" --lock-ssh-path "${LOCK_SSH_PATH}" || exit $?
 
-lock_mirror "${LOCK_SSH_URI}" "${LOCK_SSH_PATH}" || exit $?
-lock_acquired="1"
-
-setup_chroot "${BUILD_DIR}" || exit $?
-
-cat > "${BUILD_DIR}/chroot.run" <<EOF
-#!/bin/bash
-env-update && source /etc/profile
-EOF
-
-cat "${modules_basedir}/lib" >> "${BUILD_DIR}/chroot.run"
-
-cat >> "${BUILD_DIR}/chroot.run" <<EOF
-export PKGDIR="${binpkg_dir}"
-export DISTDIR="${dist_dir}"
-export PORTAGE_BINHOST="${MIRROR_HTTP_URI}"
-export USE="bindist"
-
-# Initial setup required before any action
-which layman 2>&1 > /dev/null && vrun layman -S || exit \$?
-vrun emerge --sync -v # || exit \$? # squashfs-hooks messes up this exit thing. :/
-vrun emerge -GuDNv world system || exit \$?
-EOF
+"${MODULES_BASEDIR}/_exec-module" setup-chroot --chroot-action init || exit $?
 
 # Bug: there has to be at least one argument here
 emerge_args=( -v )
@@ -65,49 +27,35 @@ if [[ "${once}" == "1" ]]; then
 	emerge_args+=( -1 )
 fi
 
-if [[ "${ACTION}" == "shell" ]]; then
-	cat >> "${BUILD_DIR}/chroot.run" <<EOF
+if [[ "${BUILD_ACTION}" == "shell" ]]; then
+	"${MODULES_BASEDIR}/_exec-module" setup_chroot --chroot-action append_stdin <<EOF
 echo "You can now edit ${BUILD_DIR}/.* files"
 echo "Exit when finished"
 vrun bash --login
 EOF
 
-elif [[ "${ACTION}" == "add" ]]; then
-	cat >> "${BUILD_DIR}/chroot.run" <<EOF
+elif [[ "${BUILD_ACTION}" == "build" ]]; then
+	"${MODULES_BASEDIR}/_exec-module" setup_chroot --chroot-action append_stdin <<EOF
 vrun emerge "${emerge_args[@]}" -bguDN "${CPV}" || exit \$?
 vrun revdep-rebuild || exit \$?
 EOF
 
-elif [[ "${ACTION}" == "remove" ]]; then
-	cat >> "${BUILD_DIR}/chroot.run" <<EOF
+elif [[ "${BUILD_ACTION}" == "remove" ]]; then
+	"${MODULES_BASEDIR}/_exec-module" setup_chroot --chroot-action append_stdin <<EOF
 vrun emerge "${emerge_args[@]}" --depclean "${CPV}" || exit \$?
 vrun revdep-rebuild || exit \$?
 EOF
 
 else
-	echo "Error: action not understood: ${ACTION}"
+	echo "Error: action not understood: ${BUILD_ACTION}"
 	usage	
 	exit 255
 fi
 
-# Sync mirror to local
-vrun rsync "${rsync_args[@]}" "${MIRROR_SSH_URI}":/"${MIRROR_SSH_PATH}"/ "${BUILD_DIR}"/"${binpkg_dir}"/ || exit $?
-
-# Copy mirror's files into place
-vrun cp -v "${BUILD_DIR}"/"${binpkg_dir}/.world" "${BUILD_DIR}"/var/lib/portage/world || exit $?
-vrun rsync --delete -av "${BUILD_DIR}"/"${binpkg_dir}/.portage/" "${BUILD_DIR}"/etc/portage/ || exit $?
+"${MODULES_BASEDIR}/_exec-module" sync --sync-action down --mirror-ssh-uri "${MIRROR_SSH_URI}" --mirror-ssh-path "${MIRROR_SSH_PATH}" --staging-ssh-uri "${STAGING_SSH_URI}" --staging-ssh-path "${STAGING_SSH_PATH}" --sync-dir "${BUILD_DIR}/binpkgs" --build-root-dir "${BUILD_DIR}" --build-binpkg-dir "${BUILD_DIR}/binpkgs" || exit $?
 
 echo "Entering chroot"
-vrun chroot "${BUILD_DIR}" /bin/bash /chroot.run; exit_status="$?"
+"${MODULES_BASEDIR}/_exec-module" setup-chroot --chroot-action execute; exit_status="$?"
 echo "Exiting chroot"
 
 if [[ "${exit_status}" != "0" ]]; then exit "${exit_status}"; fi
-
-# Copy file into local mirror copy
-vrun cp -v "${BUILD_DIR}"/var/lib/portage/world "${BUILD_DIR}"/"${binpkg_dir}"/.world || exit $?
-vrun rsync --delete -av "${BUILD_DIR}"/etc/portage/ "${BUILD_DIR}"/"${binpkg_dir}/.portage/" || exit $?
-
-# Sync local mirror copy to staging
-vrun rsync "${rsync_args[@]}" "${BUILD_DIR}"/"${binpkg_dir}"/ "${STAGING_SSH_URI}":/"${STAGING_SSH_PATH}"/ || exit $?
-# Copy staging into place on mirror
-vrun ssh "${MIRROR_SSH_URI}" rsync "${rsync_args[@]}" "${STAGING_SSH_PATH}"/ "${MIRROR_SSH_PATH}" || exit $?
diff --git a/farmerge/modules/setup-chroot b/farmerge/modules/setup-chroot
--- a/farmerge/modules/setup-chroot
+++ b/farmerge/modules/setup-chroot
@@ -1,76 +1,73 @@
 #!/bin/bash
 
-source "${MODULES_BASEDIR}/lib"
+understood_args=( "CHROOT_ACTION" "BUILD_DIR", "BUILD_BINPKG_SUBDIR", "BUILD_DIST_SUBDIR" )
+source "${LIB_BASEDIR}/variable-args" || exit $?
+check_for_required_args "${understood_args[@]}"
 
-function usage() {
-	echo "Module usage: --build-dir [/path/to/chroot/] --tarball [/path/to/tarball] --timezone-path [/usr/share/zoneinfo/timezone] [--tarball-is-stage5]"
+source "${LIB_BASEDIR}/hooks"
+
+function unmount() {
+	delete_hook exit '50-unmount-'"${BUILD_DIR}"; exit_code="$?"
+	[[ "${exit_code}" == "254" ]] && return
+	[[ "${exit_code}" != "0" ]] && return "${exit_code}"
+	
+	vrun umount "${BUILD_DIR}"/dev/pts && \
+	vrun umount "${BUILD_DIR}"/sys && \
+	vrun umount "${BUILD_DIR}"/proc
+	return $?
 }
 
-while [[ "$1" != "" ]]; do
-	if [[ "$1" == "--build-dir" ]]; then
-		if [[ "$2" == "" ]]; then
-			usage
-			exit 255
-		fi
-		build_dir="${2}"
-		shift
-	elif [[ "$1" == "--tarball" ]]; then
-		if [[ "$2" == "" ]]; then
-			usage
-			exit 255
-		fi
-		tarball="${2}"
-		shift
-	elif [[ "$1" == "--timezone-path" ]]; then
-		if [[ "$2" == "" ]]; then
-			usage
-			exit 255
-		fi
-		timezone_path="${2}"
-		shift
-	elif [[ "$1" == "--tarball-is-stage5" ]]; then
-		tarball_is_stage5="1"
-	else
-		echo "$1 not understood"
-		usage
+function mount() {
+	add_hook exit '50-unmount-'"${BUILD_DIR}" "${MODULES_BASEDIR}/_exec-module" setup-chroot --unmount --build-dir "${BUILD_DIR}"; exit_code="$?"
+	[[ "${exit_code}" == "254" ]] && return
+	[[ "${exit_code}" != "0" ]] && return "${exit_code}"
+
+	vrun mount --bind /proc "${BUILD_DIR}"/proc && \
+	vrun mount --bind /sys "${BUILD_DIR}"/sys && \
+	vrun mount --bind /dev/pts "${BUILD_DIR}"/dev/pts && \
+	vrun cp -L /etc/resolv.conf "${BUILD_DIR}"/etc/
+	
+	return $?
+}
+
+function init() {
+	mount || return $?
+
+	cat > "${BUILD_DIR}/chroot.run" <<EOF
+#!/bin/bash
+env-update && source /etc/profile
+EOF
+
+cat "${LIB_BASEDIR}/output" >> "${BUILD_DIR}/chroot.run"
+
+cat >> "${BUILD_DIR}/chroot.run" <<EOF
+export PKGDIR="${BUILD_BINPKG_SUBDIR}"
+export DISTDIR="${BUILD_DIST_SUBDIR}"
+export PORTAGE_BINHOST="${MIRROR_HTTP_URI}"
+export USE="bindist"
+
+# Initial setup required before any action
+which layman 2>&1 > /dev/null && vrun layman -S || exit \$?
+vrun emerge --sync -v # || exit \$? # squashfs-hooks messes up this exit thing. :/
+vrun emerge -GuDNv world system || exit \$?
+EOF
+}
+
+function append_stdin() {
+	cat >> "${BUILD_DIR}/chroot.run" || return $?
+}
+
+function execute() {
+	echo "Entering chroot to launch script '${BUILD_DIR}/chroot.run'..."
+	( chroot "${BUILD_DIR}" /bin/bash /chroot.run ) || return $?
+}
+
+case "${CHROOT_ACTION}" in
+	init | mount | unmount | append_stdin | execute)
+		"${CHROOT_ACTION}" || exit $?
+		;;
+	*)
+		echo "Error: action not understood: ${CHROOT_ACTION}" >&2
 		exit 255
-	fi
-	shift
+		;;
 done
-
-if [[ ! -n "${build_dir}" ]]; then
-	echo "--build-dir required, but not given"
-	usage
-	exit 255
-fi
-if [[ ! -n "${tarball}" ]]; then
-	echo "--tarball required, but not given"
-	usage
-	exit 255
-fi
-if [[ ! -n "${timezone_path}" ]]; then
-	echo "--timezone-path required, but none given"
-	usage
-	exit 255
-fi
-
-if [[ "${tarball}" == *stage5* ]]; then
-	tarball_is_stage5="1"
-else
-	echo "WARNING: this may not be a stage5 tarball!"
-	echo "Please cancel this if you are not using a stage5 tarball, unless you know what you're doing!"
-	sleep 5
-fi
-
-if [[ ! -n "${tarball_is_stage5}" ]]; then
-	echo "--tarball ought to reference a stage5 tarball, or whichever has the most packages."
-	echo "If you are certain the tarball specified is a the right one, append --tarball-is-stage5 to arguments"
-	usage
-	exit 255
-fi
-
-vrun mkdir "${build_dir}" && \
-vrun tar -xvpf "${tarball}" -C "${build_dir}" && \
-vrun chmod +rx "${build_dir}" && \
-vrun ln -sf "${timezone_path}" "${build_dir}/etc/localtime"
-exit $?
