Lots of farmerge bugfixes

diff --git a/farmerge/modules/setup-chroot b/farmerge/modules/setup-chroot
--- a/farmerge/modules/setup-chroot
+++ b/farmerge/modules/setup-chroot
@@ -1,46 +1,43 @@
 #!/bin/bash
 
-understood_args=( "CHROOT_ACTION" "BUILD_DIR", "BUILD_BINPKG_SUBDIR", "BUILD_DIST_SUBDIR" )
+understood_args=( "CHROOT_ACTION" "BUILD_DIR" "BUILD_BINPKG_SUBDIR" "BUILD_DIST_SUBDIR" )
 source "${LIB_BASEDIR}/variable-args" || exit $?
-check_for_required_args "${understood_args[@]}"
+check_for_required_args "${understood_args[@]}" || exit $?
 
 source "${LIB_BASEDIR}/hooks"
+source "${LIB_BASEDIR}/output"
 
 function unmount() {
-	delete_hook exit '50-unmount-'"${BUILD_DIR}"; exit_code="$?"
-	[[ "${exit_code}" == "254" ]] && return
-	[[ "${exit_code}" != "0" ]] && return "${exit_code}"
+	delete_hook exit '50-unmount-'"$(basename ${BUILD_DIR})"; exit_code="$?"
+	[[ "${exit_code}" != "254" ]] && [[ "${exit_code}" != "0" ]] && return "${exit_code}"
 	
-	vrun umount "${BUILD_DIR}"/dev/pts && \
-	vrun umount "${BUILD_DIR}"/sys && \
-	vrun umount "${BUILD_DIR}"/proc
-	return $?
+	vrun umount "${BUILD_DIR}"/dev/pts || return $?
+	vrun umount "${BUILD_DIR}"/sys || return $?
+	vrun umount "${BUILD_DIR}"/proc || return $?
 }
 
 function mount() {
-	add_hook exit '50-unmount-'"${BUILD_DIR}" "${MODULES_BASEDIR}/_exec-module" setup-chroot --unmount --build-dir "${BUILD_DIR}"; exit_code="$?"
+	add_hook exit '50-unmount-'"$(basename ${BUILD_DIR})" "${MODULES_BASEDIR}/_exec-module" setup-chroot --chroot-action unmount --build-dir "${BUILD_DIR}" --build-binpkg-subdir "${BUILD_BINPKG_SUBDIR}" --build-dist-subdir "${BUILD_DIST_SUBDIR}"; exit_code="$?"
 	[[ "${exit_code}" == "254" ]] && return
 	[[ "${exit_code}" != "0" ]] && return "${exit_code}"
 
-	vrun mount --bind /proc "${BUILD_DIR}"/proc && \
-	vrun mount --bind /sys "${BUILD_DIR}"/sys && \
-	vrun mount --bind /dev/pts "${BUILD_DIR}"/dev/pts && \
-	vrun cp -L /etc/resolv.conf "${BUILD_DIR}"/etc/
-	
-	return $?
+	vrun mount --bind /proc "${BUILD_DIR}"/proc || return $?
+	vrun mount --bind /sys "${BUILD_DIR}"/sys || return $?
+	vrun mount --bind /dev/pts "${BUILD_DIR}"/dev/pts || return $?
+	vrun cp -L /etc/resolv.conf "${BUILD_DIR}"/etc/ || return $?
 }
 
 function init() {
 	mount || return $?
 
-	cat > "${BUILD_DIR}/chroot.run" <<EOF
+	cat > "${BUILD_DIR}/chroot.run" <<EOF || return $?
 #!/bin/bash
 env-update && source /etc/profile
 EOF
 
-cat "${LIB_BASEDIR}/output" >> "${BUILD_DIR}/chroot.run"
+cat "${LIB_BASEDIR}/output" >> "${BUILD_DIR}/chroot.run" || return $?
 
-cat >> "${BUILD_DIR}/chroot.run" <<EOF
+cat >> "${BUILD_DIR}/chroot.run" <<EOF || return $?
 export PKGDIR="${BUILD_BINPKG_SUBDIR}"
 export DISTDIR="${BUILD_DIST_SUBDIR}"
 export PORTAGE_BINHOST="${MIRROR_HTTP_URI}"
@@ -59,8 +56,13 @@ function append_stdin() {
 
 function execute() {
 	echo "Entering chroot to launch script '${BUILD_DIR}/chroot.run'..."
-	( chroot "${BUILD_DIR}" /bin/bash /chroot.run ) || return $?
+	chroot "${BUILD_DIR}" /bin/bash /chroot.run || return $?
 }
+
+if [[ ! -d "${BUILD_DIR}" ]]; then
+	echo "Error: build dir doesn't exist: ${BUILD_DIR}"
+	exit 255
+fi
 
 case "${CHROOT_ACTION}" in
 	init | mount | unmount | append_stdin | execute)
@@ -70,4 +72,4 @@ case "${CHROOT_ACTION}" in
 		echo "Error: action not understood: ${CHROOT_ACTION}" >&2
 		exit 255
 		;;
-done
+esac
