Lots of bug fixes

diff --git a/squashfs-portage/pre-sync.d/20-squashfs b/squashfs-portage/pre-sync.d/20-squashfs
--- a/squashfs-portage/pre-sync.d/20-squashfs
+++ b/squashfs-portage/pre-sync.d/20-squashfs
@@ -27,7 +27,6 @@ for date in ${dates_to_try[@]}; do
 	BASENAME="portage-${date}.squashfs"
 	URI="${SQUASHFS_BASEURI}/${BASENAME}"
 	FILE="${SQUASHFS_BASEDIR}/${BASENAME}"
-	FILESIZE=$(stat -c%s "${FILENAME}")
 	if [[ -f "${FILE}" ]]; then
 		FETCHCOMMAND="$(source ${ROOT}/etc/make.globals && echo $RESUMECOMMAND)"
 	else
@@ -42,16 +41,12 @@ for date in ${dates_to_try[@]}; do
 
 	if [[ "$exit_code" == "8" ]]; then
 		einfo "Date too far into the future; trying again"
+		rm -f "${FILE}"
 	elif [[ "$exit_code" != "0" ]]; then
 		ewarn
 		ewarn "wget failed to fetch ${URI}"
 		ewarn
 	else
-		if [[ "${FILESIZE}" == "$(stat -c%s ${FILENAME})" ]]; then
-			no_change="1"
-		else
-			no_change="0"
-		fi
 		break
 	fi
 done
@@ -65,29 +60,30 @@ fi
 
 einfo "squashfs successfully synced!"
 
-if [[ "no_change" == "0" ]]; then
-	# -f is required on rm to keep rm from dying on a non-existant link
-	# -f is required on ln to keep ln from dying on an existing link
-	# May the -f be with them.
-	rm -f "$(realpath ${SQUASHFS_LATESTSYM})" && \
+# -f is required on rm to keep rm from dying on a non-existant link
+# -f is required on ln to keep ln from dying on an existing link
+# May the -f be with them.
+if [[ "$(realpath ${SQUASHFS_LATESTSYM} 2> /dev/null)" != "$(realpath ${FILE}  2> /dev/null)" ]]; then
+	rm -f "$(realpath ${SQUASHFS_LATESTSYM} 2> /dev/null)" && \
 	ln -f -s "${FILE}" "${SQUASHFS_LATESTSYM}"
 	exit_code="$?"
+fi
 
-	if [[ "$exit_code" != "0" ]]; then
-		eerror
-		eerror "The latest squashfs image could not be moved into place!"
-		eerror
-		exit "${exit_code}"
-	fi
+if [[ "$exit_code" != "0" ]]; then
+	eerror
+	eerror "The latest squashfs image could not be moved into place!"
+	eerror
+	exit "${exit_code}"
+fi
 
-	"${ROOT}"/usr/lib/squashfs-portage/bin/squashfs-portage-mount --remount
-	exit_code="$?"
-	if [[ "$exit_code" != "0" ]]; then
-		ewarn
-		ewarn "Could not remount the squashfs image. Please execute the following by hand:"
-		ewarn "\"${ROOT}/usr/lib/squashfs-portage/bin/squashfs-portage-mount\" --remount"
-		ewarn
-	fi
+einfo "(Re)mounting squashfs..."
+"${ROOT}"/usr/lib/squashfs-portage/bin/squashfs-portage-mount --remount
+exit_code="$?"
+if [[ "$exit_code" != "0" ]]; then
+	ewarn
+	ewarn "Could not remount the squashfs image. Please execute the following by hand:"
+	ewarn "\"${ROOT}/usr/lib/squashfs-portage/bin/squashfs-portage-mount\" --remount"
+	ewarn
 fi
 
 kill "${PPID}" # stops portage from --syncing the tree
